REFACTOR: format files

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -4,7 +4,10 @@
 set -eo pipefail
 
 echo "[+] Running $0 with pid: $$"
-type stow 1>/dev/null 2>&1 || { echo "[!] GNU Stow is required" >&2; exit 1; }
+type stow 1>/dev/null 2>&1 || {
+  echo "[!] GNU Stow is required" >&2
+  exit 1
+}
 
 echo "[+] GNU Stow found. Clearing existing symlink."
 stow -D -t "$HOME" .
@@ -12,5 +15,3 @@ stow -D -t "$HOME" .
 # Stow current directory into $HOME
 echo "[+] Creating fresh symlink"
 stow -t "$HOME" .
-
-
